### ISSUE TITLE
Localisation: where is the po folder?

### ISSUE THREAD

**Issue by ensag-dev** [Sanjai-Shaarugesh/Advanced-Weather#1]
Hello,
I would like to contribute. In the readme they say a "po" folder should exist.
Where is it so I can download the pot file?

**Comment by Sanjai-Shaarugesh** [comment]
Just click the refresh button

**Comment by garak** [comment]
> Just click the refresh button

it seems you didn't understand the question...

**Comment by garak** [comment]
@Sanjai-Shaarugesh the "po" folder is still missing, yet still mentioned in the readme. It looks like the question raised in this issue still applies. Would you mind to clarify it?

**Comment by ensag-dev** [comment]
Gone from the readme ah ah ah

**Comment by Sanjai-Shaarugesh** [comment]
## @ensag-dev  yes you can bro 👌

**Comment by Sanjai-Shaarugesh** [comment]
## Donate to this developer to contribute more please 💓
### ***https://buymeacoffee.com/sanjai*** 

[!["Buy Me A Coffee"](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png)](https://buymeacoffee.com/sanjai)
